name: GitGuardian Secret Scan- demo

on:
  push:
  workflow_dispatch:
  
env:
  GITGUARDIAN_API_KEY: ${{ secrets.guardian_token }}
  
jobs:
  security-scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
       fetch-depth: 0
      
    - name: Perform GitGuardian Secret Scan
      continue-on-error: true
      run: |
       pip install ggshield 
       
       echo "-------To search for secrets in Docker images----------"
       ggshield secret scan docker vulnerables/web-dvwa
       
       echo "-------To search for secrets in latest commit----------"
       ggshield secret scan --json --output result ci
       
       echo "-------To search for secrets in  the  repository----------"
       ggshield secret scan --json --output result repo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
       
       #echo "------To search for secrets in file------------ "
       #ggshield secret scan path -r <file name/path>
       
       #echo "-------To search for secretsin Pypi packages--------"
       #ggshield secret scan pypi flask
       
       #echo "-------To search for vulnerabilities in IaC files use---------"
       #ggshield iac scan <file name/path>
       
       #for more details run - 
       #ggshield secret scan --help 
 
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: scan_results
          path: result
